# ruff: noqa: D100
from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import CollectionModel as OptionalModel
from .strict_models import CollectionModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        AdvisoryItem,
        AlternativeDateItem,
        Attributes,
        Attributes1,
        AudienceLevelItem,
        AudioTracks,
        Availability,
        AvailableDevice,
        Badging,
        Campaigns,
        Channel,
        ChildTypes,
        ChildTypes1,
        Clips,
        CollectionModel,
        Collections,
        CurationConfig,
        Datum,
        DeviceAvailability,
        DeviceAvailability1,
        Fact,
        FanCriticRatingItem,
        FirstEp,
        Formats,
        FreeEpisodes,
        GenreDetail,
        GenreListItem,
        Hd,
        Image,
        Images,
        Items,
        Items1,
        Latest,
        LinkedAssets,
        Links,
        LogoItem,
        Markers,
        MediaType,
        NextClips,
        NextItems,
        NextShortforms,
        PlacementTag,
        Relationships,
        RenderHint,
        RenderHint1,
        Restriction,
        Shortforms,
        TargetAudience,
        Term,
        Trailers,
        TuneInBadging,
        TuneInBadgingEditorialTexts,
        VideoFormat,
    )
else:
    from .optional_models import (
        AdvisoryItem,
        AlternativeDateItem,
        Attributes,
        Attributes1,
        AudienceLevelItem,
        AudioTracks,
        Availability,
        AvailableDevice,
        Badging,
        Campaigns,
        Channel,
        ChildTypes,
        ChildTypes1,
        Clips,
        CollectionModel,
        Collections,
        CurationConfig,
        Datum,
        DeviceAvailability,
        DeviceAvailability1,
        Fact,
        FanCriticRatingItem,
        FirstEp,
        Formats,
        FreeEpisodes,
        GenreDetail,
        GenreListItem,
        Hd,
        Image,
        Images,
        Items,
        Items1,
        Latest,
        LinkedAssets,
        Links,
        LogoItem,
        Markers,
        MediaType,
        NextClips,
        NextItems,
        NextShortforms,
        PlacementTag,
        Relationships,
        RenderHint,
        RenderHint1,
        Restriction,
        Shortforms,
        TargetAudience,
        Term,
        Trailers,
        TuneInBadging,
        TuneInBadgingEditorialTexts,
        VideoFormat,
    )

__all__ = [
    "AdvisoryItem",
    "AlternativeDateItem",
    "Attributes",
    "Attributes1",
    "AudienceLevelItem",
    "AudioTracks",
    "Availability",
    "AvailableDevice",
    "Badging",
    "Campaigns",
    "Channel",
    "ChildTypes",
    "ChildTypes1",
    "Clips",
    "CollectionModel",
    "Collections",
    "CurationConfig",
    "Datum",
    "DeviceAvailability",
    "DeviceAvailability1",
    "Fact",
    "FanCriticRatingItem",
    "FirstEp",
    "Formats",
    "FreeEpisodes",
    "GenreDetail",
    "GenreListItem",
    "Hd",
    "Image",
    "Images",
    "Items",
    "Items1",
    "Latest",
    "LinkedAssets",
    "Links",
    "LogoItem",
    "Markers",
    "MediaType",
    "NextClips",
    "NextItems",
    "NextShortforms",
    "PlacementTag",
    "Relationships",
    "RenderHint",
    "RenderHint1",
    "Restriction",
    "Shortforms",
    "TargetAudience",
    "Term",
    "Trailers",
    "TuneInBadging",
    "TuneInBadgingEditorialTexts",
    "VideoFormat",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> CollectionModel:
    """Read a downloaded file into CollectionModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
